# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3f48ba4b809a6ba8601bf45c1f768945cd37df9095d1e496762f56c3f6529aa6ae1f3cdb005a3b34f49785b42c1ef087f9e2bc1bf8d0a4c65dc708ca42e411

test:
  secret_key_base: 717fe0b6d1f3ef0861f99f3a41d0bc651e74bd0a49ed88b453053e12ceecf80c934fdf5cb89ffbe4d373e01a19e3618a18462ef772664bcdc04243d0da0eb96b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
